apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-configmap
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  ProjectCode: {{ upper .Values.projectCode }}
  pipeline: {{ .Values.projectCode | upper | quote }}
  now: {{ now | date "2006-01-02" | quote }}
  defaultValues: {{ .Values.contact | default "1-800-000-0000" | quote }}
  {{ if eq .Values.infra.region "us-east" }}regionHumanReadable: "USA East region" {{ end}}

  {{- if eq .Values.infra.region "us-east" }}
  ha: true
  {{- end }}

  {{- with .Values.tags }}
  Machine Type: {{ .machine | default "NA" | quote }}
  Rack ID: {{ .rack | quote }}
  Storage Type: {{ .drive | upper | quote }}
  Video Card: {{ .vcard | quote }}
  {{- end }}

  Release: {{ .Release.Name }}

  Language Used: |-
    {{- range .Values.LangUsed }}
    - {{ . | title | quote }}
    {{- end }}
    {{- range $index, $val := .Values.LangUsed }}
    - {{ $index }} : {{ $val }}
    {{- end }}

  {{- $myvar := "This is my local variable" }}
  localVariable: {{ $myvar }}
